#!/bin/bash -l
#
#SBATCH --job-name=COSC3500_Assignment
#SBATCH --nodes=2
#SBATCH --ntasks=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --gres gpu:1
#SBATCH --nodelist=vgpu10-0,vgpu10-1
#SBATCH --time=0-00:15:00
#You could add these to your bashrc if you wanted
module load compiler-rt/latest
module add mkl/latest
module add mpi/openmpi-x86_64
module load cuda/11.1

#I would have expected the module loads to add these, but apparently not
export PATH=/opt/local/stow/cuda-11.1/bin:$PATH
export PATH=/usr/lib64/openmpi/bin:$PATH

make clean
make all

#"map-by node" (assigns processes per node. i.e. to make sure they're running on separate nodes, not all on the same node)
#"bind-to none" (for whatever reason, by default mpiexec will lock to a single core (i.e. single-threaded), bind-to none means the mpi process is free to use whatever cores it wants)
mpiexec -n 2 -map-by node -bind-to none ./Assignment1_GradeBot 2048 4 1 1 1
