#!/bin/bash
#SBATCH --job-name=COSC3500_Benchmark
#SBATCH --partition=cosc
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=1G # memory
#SBATCH --time=0-00:10 # time (D-HH:MM)

for i in 0 1 2 3
do
    make clean
    make game_of_life OFLAG='-O'$i

    # Grid size: 10x10
    time ./game_of_life -i 1000 --seed 1 -s 10x10 -v
    time ./game_of_life -i 1000 --seed 2 -s 10x10 -v
    time ./game_of_life -i 1000 --seed 42 -s 10x10 -v

    # Grid size: 100x100
    time ./game_of_life -i 1000 --seed 1 -s 100x100 -v
    time ./game_of_life -i 1000 --seed 2 -s 100x100 -v
    time ./game_of_life -i 1000 --seed 42 -s 100x100 -v

    # Grid size: 1000x1000
    time ./game_of_life -i 1000 --seed 1 -s 1000x1000 -v
    time ./game_of_life -i 1000 --seed 2 -s 1000x1000 -v
    time ./game_of_life -i 1000 --seed 42 -s 1000x1000 -v

done
